# Generates src/card.js (1200x630 social card PNG, base64). Run: python3 scripts/make-card.py
import base64, io
from PIL import Image, ImageDraw, ImageFont
W,H=1200,630
im=Image.new("RGB",(W,H),"#f4f3ef"); d=ImageDraw.Draw(im)
def f(sz,bold=False):
    for p in ["/System/Library/Fonts/Supplemental/Arial Bold.ttf" if bold else "/System/Library/Fonts/Supplemental/Arial.ttf"]:
        try: return ImageFont.truetype(p,sz)
        except: pass
    return ImageFont.load_default()
d.rectangle([0,0,W,14],fill="#f38020")
# cloud
d.ellipse([90,150,190,250],fill="#f38020"); d.ellipse([140,110,270,240],fill="#f38020"); d.rounded_rectangle([90,190,300,250],30,fill="#f38020")
d.text((330,135),"CF Cost",font=f(110,True),fill="#1b1b18")
d.text((90,320),"What Cloudflare actually charges you.",font=f(56,True),fill="#1b1b18")
d.text((90,410),"10 seconds. Read-only token. Nothing stored.",font=f(40),fill="#6b6a63")
d.text((90,530),"cfcost.com",font=f(40,True),fill="#f38020")
b=io.BytesIO(); im.save(b,"PNG",optimize=True); im.save("/tmp/card-preview.png") if False else None
open("src/card.js","w").write("// Generated by scripts/make-card.py\nexport const CARD_PNG_B64 = '%s';\n"%base64.b64encode(b.getvalue()).decode())
print(len(b.getvalue()))
